"""ApiKeyStore — async lookup and create for the v1_resume_matching_api_keys table.

Public API only stores hashed keys. Plaintext is generated by the
create-key script, returned once, and never persisted. The hash uses
sha256 — no PBKDF2/argon2 because these are 256-bit random secrets, not
human-chosen passwords; brute-forcing the hash is computationally
indistinguishable from brute-forcing the key itself.
"""

from __future__ import annotations

import hashlib
import secrets
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional, Tuple

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncEngine

from v1.resume_matching.storage.schema import v1_resume_matching_api_keys


# Generated keys look like `mnk_<43 chars urlsafe>`. The `mnk_` prefix
# makes them grep-able in logs and obvious in support contexts; the
# urlsafe body avoids URL-encoding pain when callers paste them around.
KEY_PREFIX = "mnk_"
RAW_KEY_BYTES = 32  # → 43 urlsafe chars after b64 encoding


@dataclass
class ApiKeyRecord:
    id: int
    name: str
    key_prefix: str
    created_at: datetime
    revoked_at: Optional[datetime]

    @property
    def is_active(self) -> bool:
        return self.revoked_at is None


def hash_key(plaintext: str) -> str:
    """Hex sha256 of the plaintext key — what we store and look up by."""
    return hashlib.sha256(plaintext.encode("utf-8")).hexdigest()


def generate_key() -> Tuple[str, str, str]:
    """Mint a new plaintext key. Returns (plaintext, prefix, hash).

    Caller is responsible for inserting the row and returning the
    plaintext to the operator exactly once.
    """
    body = secrets.token_urlsafe(RAW_KEY_BYTES)
    plaintext = f"{KEY_PREFIX}{body}"
    prefix = plaintext[:12]  # 4-char "mnk_" + first 8 chars of body
    return plaintext, prefix, hash_key(plaintext)


class ApiKeyStore:

    def __init__(self, engine: AsyncEngine) -> None:
        self._engine = engine

    async def create(self, *, name: str) -> Tuple[str, ApiKeyRecord]:
        """Mint and persist a new key. Returns (plaintext, record).

        Plaintext is the only opportunity to capture the secret — it is
        not stored anywhere. The caller (typically a CLI script) must
        surface it to the operator immediately.
        """
        plaintext, prefix, key_hash = generate_key()
        # Compute created_at client-side and pass it explicitly. Avoids the
        # INSERT...RETURNING dance, which Postgres + SQLite support but
        # aiomysql/pymysql don't — and lets us return the same datetime we
        # stored without a follow-up SELECT.
        created_at = datetime.now(timezone.utc)
        async with self._engine.begin() as conn:
            result = await conn.execute(
                v1_resume_matching_api_keys.insert().values(
                    name=name,
                    key_prefix=prefix,
                    key_hash=key_hash,
                    created_at=created_at,
                )
            )
            new_id = result.inserted_primary_key[0]
        record = ApiKeyRecord(
            id=new_id, name=name, key_prefix=prefix,
            created_at=created_at, revoked_at=None,
        )
        return plaintext, record

    async def lookup(self, plaintext: str) -> Optional[ApiKeyRecord]:
        """Resolve a plaintext key to its record, or None if missing/revoked.

        Returns None for both "no such key" and "key was revoked" so the
        auth dependency can return a single 401 without leaking which
        case it hit.
        """
        if not plaintext or not plaintext.startswith(KEY_PREFIX):
            return None
        key_hash = hash_key(plaintext)
        async with self._engine.connect() as conn:
            result = await conn.execute(
                select(v1_resume_matching_api_keys).where(
                    v1_resume_matching_api_keys.c.key_hash == key_hash
                )
            )
            row = result.fetchone()
        if row is None:
            return None
        record = ApiKeyRecord(
            id=row.id, name=row.name, key_prefix=row.key_prefix,
            created_at=row.created_at, revoked_at=row.revoked_at,
        )
        if not record.is_active:
            return None
        return record

    async def list_all(self) -> list[ApiKeyRecord]:
        """Return every key in the table (active + revoked), oldest first.

        Used by the operator CLI to audit keys. Includes revoked rows so
        the partner-name → ID history is visible after rotation.
        """
        async with self._engine.connect() as conn:
            result = await conn.execute(
                select(v1_resume_matching_api_keys).order_by(
                    v1_resume_matching_api_keys.c.id
                )
            )
            rows = result.fetchall()
        return [
            ApiKeyRecord(
                id=r.id, name=r.name, key_prefix=r.key_prefix,
                created_at=r.created_at, revoked_at=r.revoked_at,
            )
            for r in rows
        ]

    async def revoke_by_id(self, key_id: int) -> bool:
        """Mark a key as revoked. Returns True if a row was updated.

        Idempotent: revoking an already-revoked key is a no-op (we don't
        bump revoked_at). Operator sees a False return as "id not found
        or already revoked".
        """
        from datetime import datetime, timezone
        async with self._engine.begin() as conn:
            result = await conn.execute(
                update(v1_resume_matching_api_keys)
                .where(v1_resume_matching_api_keys.c.id == key_id)
                .where(v1_resume_matching_api_keys.c.revoked_at.is_(None))
                .values(revoked_at=datetime.now(timezone.utc))
            )
            return result.rowcount > 0

    async def revoke_by_name(self, name: str) -> int:
        """Revoke every active key with this `name`. Returns count revoked.

        A partner may have multiple historical keys (after rotations); this
        marks every still-active one. Returns 0 if no active rows match.
        """
        from datetime import datetime, timezone
        async with self._engine.begin() as conn:
            result = await conn.execute(
                update(v1_resume_matching_api_keys)
                .where(v1_resume_matching_api_keys.c.name == name)
                .where(v1_resume_matching_api_keys.c.revoked_at.is_(None))
                .values(revoked_at=datetime.now(timezone.utc))
            )
            return result.rowcount
